### ISSUE TITLE
Want to use cleanup after move, but run into error

### ISSUE THREAD

**Issue by albertusQuelle** [007revad/Synology_docker_cleanup#10]
Hi, 
after moving to the SSD my containers start failing (some reason like [here ](https://github.com/007revad/Synology_app_mover/issues/149#issue-2754045052) so i wanted to use this script to cleanup. 

![image](https://github.com/user-attachments/assets/6bbbaf2f-da5f-4fb5-8b3a-4b71a6981d1f)

**Comment by 007revad** [comment]
You would get that error is the script is running sh instead of bash. So the shell is ignoring the `#!/usr/bin/env bash` shebang at the top of the script.

Are you CDing to the folder containing syno_docker_cleanup.sh and then running it as `syno_docker_cleanup.sh`?

You'd need to run it as `./syno_docker_cleanup.sh`

Or `bash syno_docker_cleanup.sh`

Or maybe you have installed dash via Entware?

**Comment by albertusQuelle** [comment]
Thank you! That was the trick :)
![image](https://github.com/user-attachments/assets/e474ac0c-df7f-4b71-ae26-8cea3add39c5)

But i cant find those little dot with .syno.bak reference

![image](https://github.com/user-attachments/assets/4565fa45-9bfc-44b1-ba8b-e83f8e6e850e)

**Comment by 007revad** [comment]
I'm not sure what causes the <container-name>.syno.bak containers but not everyone has them.

I should change the script to check if there are any <container-name>.syno.bak containers and only show those instructions if there are some .syno.bak containers.
